apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: microservices-sso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: sa-password
        - name: MSSQL_PID
          value: "Express"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: sqlserver-storage
          mountPath: /var/opt/mssql
      volumes:
      - name: sqlserver-storage
        persistentVolumeClaim:
          claimName: sqlserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
  namespace: microservices-sso
spec:
  selector:
    app: sqlserver
  ports:
  - port: 1433
    targetPort: 1433
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: microservices-sso
type: Opaque
data:
  sa-password: WW91clN0cm9uZ0BQYXNzdzByZA== # YourStrong@Passw0rd in base64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
  namespace: microservices-sso
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 